<a href="https://colab.research.google.com/github/Gci04/AML-DS-2021/blob/main/notebooks/AML_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Week 1: Introduction  
```
- Advanced Machine Learning, Innopolis University 
- Professor: Muhammad Fahim 
- Teaching Assistant: Gcinizwe Dlamini
```
<hr>


```
Lab Plan
1. Creating a Data Science Repository (i.e Github)
2. Deep leaning Frameworks
3. About PyTorch and Torchvision installation
4. Simple Neural network 
5. About Tensforflow and tensorboard installation
6. Tensorboard example
7. Lab Task
```


## 1. Creating a Data Science Repository

Data science code quality is about correctness and reproducibility. Being a Data Scientist doesn't give you permission to write understandable code. 

### Structure of your code or project layout is very important 
```Ah thats software engineering stuff ..blah blah blah!```

Here are the key points for project sctructure : 
1. Start with a clean structure
2. Make logical structure
3. Consistancy
4. Information and Knowledge Sharing is key

```Remember: You are not working alone!!```

### Version Control Systems (Github, GitLab, ... )

Porposed simple Structure of project 


```
├── .gitignore               <- .gitignore files in sub folders if needed
├── conda_env.yml            <- Conda environment definition 
├── LICENSE
├── README.md                <- The top-level README for developers using this project.
├── requirements.txt         <- The requirements file for reproducing the analysis environment, e.g.
│                               generated with `pip freeze > requirements.txt`.
├── setup.py                 <- Metadata about your project for easy distribution.
│
├── data                     <- Data Folder
├── docs                     <- Documentation
│
├── notebooks                <- Notebooks for analysis and testing
│   ├── eda                  <- Notebooks for EDA
│   │   └── example.ipynb    <- Example python notebook
│   ├── features             <- Notebooks for generating and analysing features (1 per feature)
│   ├── modelling            <- Notebooks for modelling
│   └── preprocessing        <- Notebooks for Preprocessing 
├── scripts                  <- Standalone scripts
│   ├── train.py           <- Example sctipt
│   ├── test.py              <- Example sctipt
│   └── example.py           <- Example sctipt
│
├── src                      <- Code for use in this project.
│
└── tests                    <- Test cases
    ├── test_notebook.py     <- Example testing that Jupyter notebooks run without errors
    └── pipeline             <- pipeline tests

```

In this course we will use gitHub

### ***Git Actions***

### DEMO on Github

## 2. Deep Learning Frameworks 

The several deep learning frameworks designed & backed by big tech, universities, and researchers.
Here is the example of popular : 

1. Tensorflow
1. Keras
1. PyTorch
1. Apache MXNet
1. Microsoft Cognitive Toolkit
1. Caffe

### In this course we will focus on PyTorch and Tensorflow

## 3. About PyTorch and Torchvision installation

PyTorch a deep learning framework was released by Facebook in 2017 : <br> Installation in python with pip


**Main componets :**

1. Tensor - Similar to NumPy’s ndarrays, except that tensors can run on accelerators (i.e GPU).
2. Datasets & DataLoaders
3. Neural Network
4. Model Training (back propagation)
5. Optimization
6. Model Saving


In [1]:
# !pip3 install torch #Installation 
import torch 

### 3.1 [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

* Can be created from normal list, random or constant values, numpy array and from another tensor
* Supports Numpy operations most (tensor.multiply(), ..)
* Tensor method with underscore (``_``) performs operations in place (i.e tensor.add_(2))
* Can be converted to numpy 

In [2]:
#initialization 
data = [[5, 6, 1],[3, 4, 5],[4, 3, 6]]
tensor_x = torch.tensor(data) # by default in CPU

print(f"Shape of tensor: {tensor_x.shape}")
print(f"Datatype of tensor: {tensor_x.dtype}")
print(f"tensor device : {tensor_x.device}")

Shape of tensor: torch.Size([3, 3])
Datatype of tensor: torch.int64
tensor device : cpu


In [3]:
import numpy as np

tensor_x2 = torch.from_numpy(np.ones((5,5)))
print(tensor_x2.add(5))
print(tensor_x2)

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]], dtype=torch.float64)
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [4]:
tensor_x2.add_(7)
print(tensor_x2)

tensor([[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]], dtype=torch.float64)


### 3.2 [Datasets & DataLoaders](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html)

* For Smooth data loading and preprocessing 

### 3.3 Neural Network

* ```torch.nn``` provides all the building blocks to build own neural network

In [5]:
from torch import nn
device = 'cuda' if torch.cuda.is_available() else 'cpu' # get device for training model 

class NeuralNetwork(nn.Module):
    def __init__(self,input_dim=50,output_dim=1):
        super(NeuralNetwork, self).__init__()
        self.layer1 = nn.Linear(input_dim, 50)
        self.layer2 = nn.Linear(50, 25)
        self.output = nn.Linear(25, output_dim)

    def forward(self, x):
        x = torch.tanh(self.layer1(x)) 
        x = torch.tanh(self.layer2(x))
        x = torch.sigmoid(self.output(x))
        return x

In [6]:
model = NeuralNetwork().to(device)
print(model)

X = torch.rand(1, 50, device=device)
print(f"Neural Network output : {model(X)}")

NeuralNetwork(
  (layer1): Linear(in_features=50, out_features=50, bias=True)
  (layer2): Linear(in_features=50, out_features=25, bias=True)
  (output): Linear(in_features=25, out_features=1, bias=True)
)
Neural Network output : tensor([[0.4958]], device='cuda:0', grad_fn=<SigmoidBackward>)


In [7]:
#print the model parameters
for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Layer: layer1.weight | Size: torch.Size([50, 50]) | Values : tensor([[ 0.0174,  0.0172,  0.1399, -0.0488,  0.1109,  0.0186,  0.0863,  0.0937,
         -0.0462, -0.1145, -0.1261,  0.0374,  0.0762,  0.0576,  0.1312,  0.0706,
         -0.0480,  0.0749, -0.0446,  0.0737, -0.0049,  0.1136, -0.1226,  0.0338,
         -0.0750,  0.0491,  0.0274, -0.0235, -0.0896,  0.1356, -0.1012, -0.0484,
          0.0211,  0.0696,  0.0554, -0.0801,  0.0242,  0.0830,  0.0153, -0.1392,
          0.1359,  0.1222,  0.0125,  0.1011, -0.0561,  0.0300, -0.0077, -0.0418,
          0.0958,  0.0370],
        [ 0.0132, -0.0178, -0.1153, -0.1064,  0.0727, -0.0087,  0.0211, -0.1334,
         -0.0087,  0.1287,  0.0430, -0.0505, -0.0176,  0.1134,  0.1075,  0.0662,
         -0.0055,  0.0428, -0.0273, -0.0594, -0.0714,  0.0818, -0.0009,  0.1136,
         -0.0270,  0.1028,  0.1210,  0.0597, -0.0465, -0.1389, -0.0847, -0.1128,
          0.0451,  0.0487,  0.0289, -0.1082,  0.0514, -0.0487, -0.0422, -0.1054,
         -0.0584,  0

In [8]:
device

'cuda'

### Neural Network Training

* What are the parameters for training a neural network? 
* What are the steps for training a neural network? 

### Dataset loading and Preprocessing 

In [9]:
from torch.utils.data import DataLoader, TensorDataset
train_x = torch.from_numpy(np.random.normal(1,1,(640,50))).float()
train_y = torch.from_numpy(np.random.randint(0,2,(640,1))).float()

test_x = torch.from_numpy(np.random.normal(1,1,(192,50))).float()
test_y = torch.from_numpy(np.random.randint(0,2,(192,1))).float()

train_DataLoader = DataLoader(TensorDataset(train_x,train_y), batch_size=64)
test_DataLoader = DataLoader(TensorDataset(test_x,test_y))

### The optimizer and Loss function 

* ```torch.optim``` module contains different optimizers available in PyTorch such as SGD, ADAM and RMSProp

**Inside the training loop**
* Reset the gradients of model parameters ```optimizer.zero_grad()```
* After foward pass, calculate loss using specified loss function and then backpropagate the loss ```loss.backwards()```
* Adjust the weights of the Network ```optimizer.step()```

**What Loss function to choose ?**
* For Regression
* For Classification

In [13]:
import torch.optim as optim

# Alternatively, you can use a Sequential model
# model = nn.Sequential(...).to(device)

model = NeuralNetwork().float().to(device)

lr = 1e-1
n_epochs = 100

#nn.MSELoss(reduction='mean'), torch.nn.CrossEntropyLoss()

loss_fn = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=lr)


def make_train_step(model, loss_fn, optimizer):
    def train_step(x,y):
        model.train() #set model to training mode
        ypred = model(x.to(device)) #Foward pass
        loss = loss_fn(ypred.to(device),y.to(device)) # Calcutation of loss
        loss.backward() 

        optimizer.step()
        optimizer.zero_grad()

        return loss.item()

    return train_step


train_step = make_train_step(model, loss_fn, optimizer)
losses = []

In [14]:
# Training loop
for epoch in range(n_epochs):
    # Performs one train step and returns the corresponding loss
    for X,y in train_DataLoader:
        loss = train_step(X, y.float())
        losses.append(loss)
        

### How to monitor the Neural network training/optimization progress? 

### About Tensforflow, tensorboard installation and example

* Tracking and visualizing metrics (Accuracy, loss, ...)
* To install tensorboard : ```pip install torch torchvision```

In [ ]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter()

In [ ]:
# Training loop
for epoch in range(n_epochs):
    l = 0.0
    size = len(train_DataLoader.dataset)
    # Performs one train step and returns the corresponding loss
    for X,y in train_DataLoader:
        loss = train_step(X, y.float())
        l += (loss/size)
        losses.append(loss)
    writer.add_scalar("Loss/train", loss, epoch)
    for tag, parm in model.named_parameters():
        writer.add_histogram(tag, parm.grad.data.cpu().numpy(), epoch)

dummy_input = torch.autograd.Variable(torch.rand(1, 50))
writer.add_graph(model=model, input_to_model=(dummy_input, ))
writer.close()

In [ ]:
!ls

## How to save model for later use? 

## How about Tensorflow or Keras

* Tensorflow 2.0 stable version was released in October 2019 
* Tensorflow 2.0 looks more like Keras
* Represent computation as a directed acyclic graph often called Computation Graph -- same as PyTorch
* Tensorflow has static computation graph while PyTorch has Dynamic computational graph (One of major differences)
* **Now its difficult to separate the two since they both support static and dynamic**

There are 3 ways (That I know) to create a and train neural network in tensorflow 2.0 <br>
Let's see how a neural net looks like 

In [ ]:
%load_ext tensorboard

In [ ]:
import tensorflow as tf
import numpy as np

## Data
SIZE = 2000
EPOCHS = 10
x1 = np.random.normal(0, 10, SIZE)
x2 = np.random.normal(3, 5, SIZE)
x = np.dstack((x1, x2))[0]
y = (3 * np.sqrt(np.abs(x1)+0.1) + np.power(x2,3)).reshape(-1,1)

train_dataset = tf.data.Dataset.from_tensor_slices((x, y)).shuffle(100).batch(50)

### Option 1

In [ ]:
model1 = tf.keras.Sequential()
model1.add(tf.keras.layers.Dense(64, input_shape=(2,) , activation='tanh'))
model1.add(tf.keras.layers.Dense(128, activation = 'relu'))
model1.add(tf.keras.layers.Dense(1))
model1.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.MSE)
History = model1.fit(train_dataset, epochs=100)

### Option 2 

* tf.keras.Model

In [ ]:
class Model2(tf.keras.Model):
    def __init__(self):
        super(Model2, self).__init__()
        self.hidden1 = tf.keras.layers.Dense(64, input_shape=(2,) ,activation='sigmoid')
        self.hidden2 = tf.keras.layers.Dense(128, activation='relu')
        self.out = tf.keras.layers.Dense(2)
        self.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.MSE)

    def call(self, inputs):
        x = self.hidden1(inputs)
        x = self.hidden2(x)
        x = self.out(x)
        return x

model2 = Model2()
model2.fit(train_dataset, epochs=20)


## Option 3

* `tf.GradientTape()` (Mostly used in training of GANs)

In [ ]:
model3 = tf.keras.Sequential()
model3.add(tf.keras.layers.Dense(64, input_shape=(2,) , activation='sigmoid'))
model3.add(tf.keras.layers.Dense(128, activation = 'relu'))
model3.add(tf.keras.layers.Dense(1))
# model3.build()
opt =tf.keras.optimizers.Adam(0.001)
mse =tf.keras.losses.MSE
batch = 100
for i in range(10):
    for X_sample, y_sample in train_dataset:
        with tf.GradientTape() as tape:
            y_pre = model3(X_sample)
            loss = mse(y_sample, y_pre)
        grads = tape.gradient(loss, model3.trainable_variables)	
        processed_grads = [g for g in grads]
        grads_and_vars = zip(processed_grads, model3.trainable_variables)
        opt.apply_gradients(grads_and_vars)
    print ('Model3: ', i, ' : ', np.mean(loss.numpy()))

In [ ]:
#Print the model 
model3.summary()

In [ ]:
import os, datetime

model11 = tf.keras.Sequential()
model11.add(tf.keras.layers.Dense(64, input_shape=(2,) , activation='tanh'))
model11.add(tf.keras.layers.Dense(128, activation = 'relu'))
model11.add(tf.keras.layers.Dense(1))
model11.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.MSE)


x1_val = np.random.normal(0, 10, (30,1))
x2_val = np.random.normal(3, 5, (30,1))
x_val = np.hstack((x1_val, x2_val))
y_val = (3 * np.sqrt(np.abs(x1_val)+0.1) + np.power(x2_val,3))
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))

logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

model11.fit(train_dataset, epochs=5, validation_data=(x_val,y_val), callbacks=[tensorboard_callback])

In [ ]:
model11.summary()

## [Tensorboard example](https://colab.research.google.com/drive/1_HxMqsqEAHAo2vZ9aER7jCbtOlJJ4fOf?usp=sharing)

### Lab task 


```
Lab Plan
1. Create a GitHub or GitLab private repo (add Gci04 as contributor)
2. Use the example given in lab and modify it to regression task
3. Create tests (minimum 2 in tests folder)
4. Use Tensorboard
5. Modify the test script for your model and git actions script if necessary

```
