### Week 1: Introduction  
```
- Advanced Machine Learning, Innopolis University 
- Professor: Muhammad Fahim 
- Teaching Assistant: Gcinizwe Dlamini
```
<hr>


```
Lab Plan
1. Creating a Data Science Repository (i.e Github)
2. Deep leaning Frameworks
3. About PyTorch and Torchvision installation
4. Simple Neural network 
5. About Tensforflow and tensorboard installation
6. Tensorboard example
7. Lab Task
```


## 1. Creating a Data Science Repository

Data science code quality is about correctness and reproducibility. Being a Data Scientist doesn't give you permission to write understandable code. 

### Structure of your code or project layout is very important 
```Ah thats software engineering stuff ..blah blah blah!```

Here are the key points for project sctructure : 
1. Start with a clean structure
2. Make logical structure
3. Consistancy

```Remember: You are not working alone!!```

### Version Control Systems (Github, GitLab, ... )

Porposed simple Structure of project 


```
├── .gitignore               <- .gitignore files in sub folders if needed
├── conda_env.yml            <- Conda environment definition 
├── LICENSE
├── README.md                <- The top-level README for developers using this project.
├── requirements.txt         <- The requirements file for reproducing the analysis environment, e.g.
│                               generated with `pip freeze > requirements.txt`.
├── setup.py                 <- Metadata about your project for easy distribution.
│
├── data                     <- Data Folder
├── docs                     <- Documentation
│
├── notebooks                <- Notebooks for analysis and testing
│   ├── eda                  <- Notebooks for EDA
│   │   └── example.ipynb    <- Example python notebook
│   ├── features             <- Notebooks for generating and analysing features (1 per feature)
│   ├── modelling            <- Notebooks for modelling
│   └── preprocessing        <- Notebooks for Preprocessing 
├── scripts                  <- Standalone scripts
│   ├── train.py           <- Example sctipt
│   ├── test.py              <- Example sctipt
│   └── example.py           <- Example sctipt
│
├── src                      <- Code for use in this project.
│
└── tests                    <- Test cases
    ├── test_notebook.py     <- Example testing that Jupyter notebooks run without errors
    └── pipeline             <- pipeline tests

```

In this course we will use gitHub

### ***Git Actions***

## 2. Deep Learning Frameworks 

The several deep learning frameworks designed & backed by big tech, universities, and researchers.
Here is the example of popular : 

1. Tensorflow
1. Keras
1. PyTorch
1. Apache MXNet
1. Microsoft Cognitive Toolkit
1. Caffe

### In this course we will focus on PyTorch and Tensorflow

## 3. About PyTorch and Torchvision installation

PyTorch a deep learning framework was released by Facebook in 2017 : <br> Installation in python with pip


**Main componets :**

1. Tensor - Similar to NumPy’s ndarrays, except that tensors can run on accelerators (i.e GPU).
2. Datasets & DataLoaders
3. Neural Network
4. Model Training (back propagation)
5. Optimization
6. Model Saving


In [1]:
# !pip3 install torch #Installation 
import torch 

### 3.1 [Tensors](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

* Can be created from normal list, random or constant values, numpy array and from another tensor
* Supports Numpy operations most (tensor.multiply(), ..)
* Tensor method with underscore (``_``) performs operations in place (i.e tensor.add_(2))
* Can be converted to numpy 

In [2]:
#initialization 
data = [[5, 6, 1],[3, 4, 5],[4, 3, 6]]
tensor_x = torch.tensor(data) # by default in CPU

print(f"Shape of tensor: {tensor_x.shape}")
print(f"Datatype of tensor: {tensor_x.dtype}")
print(f"tensor device : {tensor_x.device}")

Shape of tensor: torch.Size([3, 3])
Datatype of tensor: torch.int64
tensor device : cpu


In [3]:
import numpy as np

tensor_x2 = torch.from_numpy(np.ones((5,5)))
print(tensor_x2.add(5))
print(tensor_x2)

tensor([[6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6.]], dtype=torch.float64)
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [4]:
tensor_x2.add_(7)
print(tensor_x2)

tensor([[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]], dtype=torch.float64)


### 3.2 [Datasets & DataLoaders](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html)

* For Smooth data loading and preprocessing 

### 3.3 Neural Network

* ```torch.nn``` provides all the building blocks to build own neural network
* 

In [5]:
from torch import nn
device = 'cuda' if torch.cuda.is_available() else 'cpu' # get device for training model 

class NeuralNetwork(nn.Module):
    def __init__(self,input_dim=50,output_dim=1):
        super(NeuralNetwork, self).__init__()
        self.layer1 = nn.Linear(input_dim, 50)
        self.layer2 = nn.Linear(50, 25)
        self.output = nn.Linear(25, output_dim)

    def forward(self, x):
        x = torch.tanh(self.layer1(x)) 
        x = torch.tanh(self.layer2(x))
        x = torch.sigmoid(self.output(x))
        return x

In [6]:
model = NeuralNetwork().to(device)
print(model)

X = torch.rand(1, 50, device=device)
print(f"Neural Network output : {model(X)}")

NeuralNetwork(
  (layer1): Linear(in_features=50, out_features=50, bias=True)
  (layer2): Linear(in_features=50, out_features=25, bias=True)
  (output): Linear(in_features=25, out_features=1, bias=True)
)
Neural Network output : tensor([[0.4591]], grad_fn=<SigmoidBackward>)


In [7]:
#print the model parameters
for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Layer: layer1.weight | Size: torch.Size([50, 50]) | Values : tensor([[ 0.0681,  0.0777,  0.1302,  0.0999,  0.0502,  0.0643,  0.0423, -0.0625,
         -0.0589,  0.0760, -0.0025,  0.0705, -0.1122, -0.0752,  0.1097, -0.0326,
          0.0510, -0.1357,  0.1046,  0.1394,  0.0473, -0.0206,  0.1410,  0.0810,
         -0.0061,  0.0333, -0.0970,  0.0895, -0.0222,  0.1049,  0.0680,  0.0628,
         -0.0023, -0.1297,  0.0028, -0.1277, -0.0699, -0.1185,  0.0954, -0.0112,
         -0.0023, -0.0192, -0.0161,  0.0661, -0.0249,  0.1023, -0.0680, -0.0673,
         -0.0386,  0.0416],
        [ 0.0407, -0.1043,  0.0366,  0.1404, -0.0005, -0.0299,  0.0626,  0.0293,
         -0.1253,  0.0812,  0.0672,  0.1199, -0.0225,  0.0533,  0.0095,  0.1208,
         -0.0865, -0.1353,  0.1041,  0.0423,  0.0474,  0.1395, -0.0389, -0.1005,
          0.1332,  0.0516,  0.1173,  0.1022,  0.1348, -0.0628, -0.0869, -0.0579,
         -0.0462, -0.0183, -0.0448, -0.0191, -0.0259,  0.1312,  0.0584,  0.0089,
         -0.0884, -0

### Neural Network Training

* What are the parameters for training a neural network? 
* What are the steps for training a neural network? 

### Dataset loading and Preprocessing 

In [8]:
from torch.utils.data import DataLoader, TensorDataset
train_x = torch.from_numpy(np.random.normal(1,1,(640,50))).float()
train_y = torch.from_numpy(np.random.randint(0,2,(640,1))).float()

test_x = torch.from_numpy(np.random.normal(1,1,(192,50))).float()
test_y = torch.from_numpy(np.random.randint(0,2,(192,1))).float()

train_DataLoader = DataLoader(TensorDataset(train_x,train_y), batch_size=64)
test_DataLoader = DataLoader(TensorDataset(test_x,test_y))

### The optimizer and Loss function 

* ```torch.optim``` module contains different optimizers available in PyTorch such as SGD, ADAM and RMSProp

**Inside the training loop**
* Reset the gradients of model parameters ```optimizer.zero_grad()```
* After foward pass, calculate loss using specified loss function and then backpropagate the loss ```loss.backwards()```
* Adjust the weights of the Network ```optimizer.step()```

**What Loss function to choose ?**
* For Regression
* For Classification

In [9]:
import torch.optim as optim

# Alternatively, you can use a Sequential model
# model = nn.Sequential(...).to(device)

model = NeuralNetwork().float()

lr = 1e-1
n_epochs = 100

#nn.MSELoss(reduction='mean'), torch.nn.CrossEntropyLoss()

loss_fn = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=lr)


def make_train_step(model, loss_fn, optimizer):
    def train_step(x,y):
        model.train() #set model to training mode
        ypred = model(x) #Foward pass
        loss = loss_fn(ypred,y) # Calcutation of loss
        loss.backward() 

        optimizer.step()
        optimizer.zero_grad()

        return loss.item()

    return train_step


train_step = make_train_step(model, loss_fn, optimizer)
losses = []

In [10]:
# # Training loop
# for epoch in range(n_epochs):
#     # Performs one train step and returns the corresponding loss
#     for X,y in train_DataLoader:
#         loss = train_step(X, y.float())
#         losses.append(loss)
        

### How to monitor the Neural network training/optimization progress? 

### About Tensforflow, tensorboard installation and example

* Tracking and visualizing metrics (Accuracy, loss, ...)
* To install tensorboard : ```pip install torch torchvision```

In [11]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter()

In [12]:
# Training loop
for epoch in range(n_epochs):
    l = 0.0
    size = len(train_DataLoader.dataset)
    # Performs one train step and returns the corresponding loss
    for X,y in train_DataLoader:
        loss = train_step(X, y.float())
        l += (loss/size)
        losses.append(loss)
    writer.add_scalar("Loss/train", l, epoch)
    for tag, parm in model.named_parameters():
        writer.add_histogram(tag, parm.grad.data.cpu().numpy(), epoch)

dummy_input = torch.autograd.Variable(torch.rand(1, 50))
writer.add_graph(model=model, input_to_model=(dummy_input, ))
# writer.add_graph(model,cc.next())
writer.close()

In [13]:
!ls

AML_Lab1.ipynb	AML_Lab2.ipynb	runs


## How to save model for later use? 

## How about Tensorflow or Keras

* Tensorflow 2.0 stable version was released in October 2019 
* Tensorflow 2.0 looks more like Keras
* Represent computation as a directed acyclic graph often called Computation Graph -- same as PyTorch
* Tensorflow has static computation graph while PyTorch has Dynamic computational graph (One of major differences)
* **Now its difficult to separate the two since they both support static and dynamic**

There are 3 ways (That I know) to create a and train neural network in tensorflow 2.0 <br>
Let's see how a neural net looks like 

In [14]:
%load_ext tensorboard

In [56]:
import tensorflow as tf
import numpy as np

## Data
SIZE = 2000
EPOCHS = 10
x1 = np.random.normal(0, 10, SIZE)
x2 = np.random.normal(3, 5, SIZE)
x = np.dstack((x1, x2))[0]
y = (3 * np.sqrt(np.abs(x1)+0.1) + np.power(x2,3)).reshape(-1,1)


In [57]:
train_dataset = tf.data.Dataset.from_tensor_slices((x, y)).shuffle(100).batch(50)

In [60]:
model1 = tf.keras.Sequential()
model1.add(tf.keras.layers.Dense(64, input_shape=(2,) , activation='tanh'))
model1.add(tf.keras.layers.Dense(128, activation = 'relu'))
model1.add(tf.keras.layers.Dense(1))
model1.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.MSE)
History = model1.fit(train_dataset, epochs=100)

Epoch 1/100
40/40 [==============================] - 0s 2ms/step - loss: 557890.6035
Epoch 2/100
40/40 [==============================] - 0s 2ms/step - loss: 556391.3125
Epoch 3/100
40/40 [==============================] - 0s 2ms/step - loss: 510444.4484
Epoch 4/100
40/40 [==============================] - 0s 2ms/step - loss: 515862.7561
Epoch 5/100
40/40 [==============================] - 0s 2ms/step - loss: 467800.2393
Epoch 6/100
40/40 [==============================] - 0s 2ms/step - loss: 437254.0480
Epoch 7/100
40/40 [==============================] - 0s 2ms/step - loss: 414434.5198
Epoch 8/100
40/40 [==============================] - 0s 2ms/step - loss: 363895.2595
Epoch 9/100
40/40 [==============================] - 0s 2ms/step - loss: 332396.7839
Epoch 10/100
40/40 [==============================] - 0s 2ms/step - loss: 278627.1301
Epoch 11/100
40/40 [==============================] - 0s 2ms/step - loss: 282298.9336
Epoch 12/100
40/40 [==============================] - 0s 2ms/st

40/40 [==============================] - 0s 3ms/step - loss: 19393.8072
Epoch 98/100
40/40 [==============================] - 0s 2ms/step - loss: 20855.9910
Epoch 99/100
40/40 [==============================] - 0s 2ms/step - loss: 20696.6412
Epoch 100/100
40/40 [==============================] - 0s 2ms/step - loss: 20223.3367


In [61]:
class Model2(tf.keras.Model):
    def __init__(self):
        super(Model2, self).__init__()
        self.hidden1 = tf.keras.layers.Dense(64, input_shape=(2,) ,activation='sigmoid')
        self.hidden2 = tf.keras.layers.Dense(128, activation='relu')
        self.out = tf.keras.layers.Dense(2)
        self.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.MSE)

    def call(self, inputs):
        x = self.hidden1(inputs)
        x = self.hidden2(x)
        x = self.out(x)
        return x

model2 = Model2()
model2.fit(train_dataset, epochs=20)


Epoch 1/20
40/40 [==============================] - 0s 2ms/step - loss: 601250.9444
Epoch 2/20
40/40 [==============================] - 0s 2ms/step - loss: 576227.6151
Epoch 3/20
40/40 [==============================] - 0s 2ms/step - loss: 541659.6947
Epoch 4/20
40/40 [==============================] - 0s 2ms/step - loss: 560583.1768
Epoch 5/20
40/40 [==============================] - 0s 2ms/step - loss: 509486.6867
Epoch 6/20
40/40 [==============================] - 0s 2ms/step - loss: 486538.1212
Epoch 7/20
40/40 [==============================] - 0s 2ms/step - loss: 429719.4604
Epoch 8/20
40/40 [==============================] - 0s 2ms/step - loss: 441913.0762
Epoch 9/20
40/40 [==============================] - 0s 2ms/step - loss: 420350.0549
Epoch 10/20
40/40 [==============================] - 0s 2ms/step - loss: 394824.6160
Epoch 11/20
40/40 [==============================] - 0s 2ms/step - loss: 379236.0932
Epoch 12/20
40/40 [==============================] - 0s 2ms/step - loss: 3

In [63]:
model3 = tf.keras.Sequential()
model3.add(tf.keras.layers.Dense(64, input_shape=(2,) , activation='sigmoid'))
model3.add(tf.keras.layers.Dense(128, activation = 'relu'))
model3.add(tf.keras.layers.Dense(1))
# model3.build()
opt =tf.keras.optimizers.Adam(0.001)
mse =tf.keras.losses.MSE
batch = 100
for i in range(10):
    for X_sample, y_sample in train_dataset:
        with tf.GradientTape() as tape:
            y_pre = model3(X_sample)
            loss = mse(y_sample, y_pre)
        grads = tape.gradient(loss, model3.trainable_variables)	
        processed_grads = [g for g in grads]
        grads_and_vars = zip(processed_grads, model3.trainable_variables)
        opt.apply_gradients(grads_and_vars)
    print ('Model3: ', i, ' : ', np.mean(loss.numpy()))

Model3:  0  :  181540.08
Model3:  1  :  219821.45
Model3:  2  :  139970.16
Model3:  3  :  260126.5
Model3:  4  :  298328.25
Model3:  5  :  179065.4
Model3:  6  :  141392.62
Model3:  7  :  219212.92
Model3:  8  :  174507.62
Model3:  9  :  147624.94


In [64]:
model3.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_36 (Dense)             (None, 64)                192       
_________________________________________________________________
dense_37 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_38 (Dense)             (None, 1)                 129       
Total params: 8,641
Trainable params: 8,641
Non-trainable params: 0
_________________________________________________________________


In [65]:
for X_sample, y_sample in train_dataset.batch(10):
    print(X_sample)

tf.Tensor(
[[[-1.81024765e+00 -4.75776023e+00]
  [-1.24076546e+01  2.88154374e+00]
  [-1.49488946e+01  2.40728908e+00]
  [-1.04139012e+01 -5.05845389e-01]
  [ 1.08387180e+01  8.63886095e+00]
  [-2.30631268e+00 -1.62200264e+00]
  [-1.24581932e+01  5.74719253e+00]
  [-8.69084750e+00  4.02942811e+00]
  [-1.85891395e+01  5.32681761e+00]
  [ 1.01446997e+01  4.38106220e+00]
  [ 1.09900010e+00 -3.35053093e+00]
  [-1.15955897e+01  2.37331358e+00]
  [ 2.88945117e+01  2.72078936e+00]
  [-1.09287410e+01  2.61919729e+00]
  [-9.34406966e+00  1.04241250e+01]
  [ 7.04328413e+00  4.56632013e+00]
  [ 1.05519939e+01 -5.33265977e-01]
  [-4.80806507e+00 -7.84073284e+00]
  [ 8.67827423e+00 -8.80253063e-01]
  [ 1.79608704e+01 -6.66007656e+00]
  [-2.25233443e+01  5.64421151e+00]
  [ 4.62664626e+00 -2.09175652e-01]
  [-6.16717145e+00 -4.95025956e+00]
  [-8.59011652e-01 -3.78765257e+00]
  [ 1.59732082e+00  8.19671399e+00]
  [ 1.52865518e+01  5.13241959e+00]
  [-1.08059630e+01 -9.46181517e+00]
  [ 2.60037144e+0

In [74]:
x_val

array([[ 12.28010163,   2.61486889],
       [ -9.1602571 ,   7.32822203],
       [  5.51952843,   9.46958471],
       [  5.15105645,   1.43135623],
       [  3.52177264,   2.02137232],
       [ 15.23260393,  -2.15383592],
       [  0.35141895,  -1.4388179 ],
       [ 11.88190106,  -8.59400212],
       [  0.70018495,   4.95230362],
       [ 20.93195987,  -0.50474121],
       [ -3.27261569,   7.15077139],
       [  1.39496098,   4.48816908],
       [  4.64766091,   5.94035124],
       [ 16.89714857,   4.82482854],
       [  9.16665096,   2.92201837],
       [ -3.02563101,  16.34022156],
       [-19.55818777,   1.09171196],
       [ -5.11435528,  -8.53690488],
       [ -7.69374744,  14.14557847],
       [ 10.80638333,  13.10838945],
       [ -9.47219872,  -1.24472407],
       [ -3.23938845,   2.02635553],
       [  0.6069377 ,   4.23006101],
       [-22.42243381,   2.1783545 ],
       [ -8.35715893,  11.31388114],
       [-19.67911814,   8.65607695],
       [ -4.56993308,  -2.45524977],
 

In [85]:
import os, datetime

model11 = tf.keras.Sequential()
model11.add(tf.keras.layers.Dense(64, input_shape=(2,) , activation='tanh'))
model11.add(tf.keras.layers.Dense(128, activation = 'relu'))
model11.add(tf.keras.layers.Dense(1))
model11.compile(optimizer=tf.keras.optimizers.Adam(0.001), loss=tf.keras.losses.MSE)


x1_val = np.random.normal(0, 10, (30,1))
x2_val = np.random.normal(3, 5, (30,1))
x_val = np.hstack((x1_val, x2_val))
y_val = (3 * np.sqrt(np.abs(x1_val)+0.1) + np.power(x2_val,3))
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))

logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)

model11.fit(train_dataset, epochs=5, validation_data=(x_val,y_val), callbacks=[tensorboard_callback])

Epoch 1/5
40/40 [==============================] - 1s 7ms/step - loss: 577411.8224 - val_loss: 96543.9766
Epoch 2/5
40/40 [==============================] - 0s 3ms/step - loss: 540068.0635 - val_loss: 86921.7344
Epoch 3/5
40/40 [==============================] - 0s 2ms/step - loss: 532481.3281 - val_loss: 74160.0234
Epoch 4/5
40/40 [==============================] - 0s 3ms/step - loss: 453524.6391 - val_loss: 64913.1250
Epoch 5/5
40/40 [==============================] - 0s 3ms/step - loss: 425221.8150 - val_loss: 57874.6758


In [80]:
model11.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_45 (Dense)             (None, 64)                192       
_________________________________________________________________
dense_46 (Dense)             (None, 128)               8320      
_________________________________________________________________
dense_47 (Dense)             (None, 1)                 129       
Total params: 8,641
Trainable params: 8,641
Non-trainable params: 0
_________________________________________________________________


In [84]:
for X_sample, y_sample in val_dataset:
    print(X_sample)
    

tf.Tensor([ 7.09255684 -0.77939412], shape=(2,), dtype=float64)
tf.Tensor([-6.20833772  4.63055028], shape=(2,), dtype=float64)
tf.Tensor([-10.26887922   8.61899868], shape=(2,), dtype=float64)
tf.Tensor([-0.62083707  3.40076628], shape=(2,), dtype=float64)
tf.Tensor([-0.07529255  6.41355516], shape=(2,), dtype=float64)
tf.Tensor([29.12383742  0.61027601], shape=(2,), dtype=float64)
tf.Tensor([13.74954667  8.33322582], shape=(2,), dtype=float64)
tf.Tensor([ 4.29627701 -3.79150227], shape=(2,), dtype=float64)
tf.Tensor([-2.54782298  9.71857999], shape=(2,), dtype=float64)
tf.Tensor([ 3.42504386 -2.96252159], shape=(2,), dtype=float64)
tf.Tensor([13.09635483  6.07144486], shape=(2,), dtype=float64)
tf.Tensor([0.19733155 0.98659904], shape=(2,), dtype=float64)
tf.Tensor([7.37379545 6.84420474], shape=(2,), dtype=float64)
tf.Tensor([8.5478648  8.67336744], shape=(2,), dtype=float64)
tf.Tensor([ 6.56667692 -5.75218784], shape=(2,), dtype=float64)
tf.Tensor([-2.90202903  1.01073971], shape=(